title: Cyber Athlete
short_title: cyA
description: Site officiel de la structure Esports Cyber Athlete
logo: /img/logo_cyA.svg
social:
  twitter: cyA_Esport
  twitch: cya_esport
baseurl:
domain: cya.fr
permalink: "/:path/"
collections:
  staff:
    people: true
    output: true
navigation:
  menu:
  - name: Twitch
    url: '/twitch'
  - name: À propos
    url: '/about'
    sass:
  sass_dir: _sass
  style: compressed
